import type { Story } from '../../types/story';

/**
 * Static story data for Kanban MVP.
 * Replace with API fetch when backend stories API exists.
 */
export const staticStories: Story[] = [
  {
    _id: '1',
    headline: 'Climate report findings',
    description: 'Analysis of the latest climate report and implications for local policy. Minimum 140 characters required for description so we pad this out to meet the requirement for the story model.',
    state: 'idea',
    ownerId: 'current-user',
    categories: ['Environment'],
    createdBy: 'current-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    headline: 'City council budget review',
    description: 'Coverage of the upcoming city council budget review session and key figures. We need at least 140 characters in the description field so here is some extra text to fill that requirement.',
    state: 'visible',
    ownerId: 'current-user',
    categories: ['Politics'],
    createdBy: 'current-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    headline: 'Local sports roundup',
    description: 'Weekly roundup of local sports events and results. Description must be at least 140 characters so we add padding here to satisfy the data model validation rules for the story.',
    state: 'scripting',
    producer: 'other-user',
    editors: ['current-user'],
    categories: ['Sports'],
    createdBy: 'other-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '4',
    headline: 'Interview: Healthcare workers',
    description: 'Interviews with frontline healthcare workers about conditions and challenges. We need 140 characters minimum for the description so this sentence helps us reach that limit for the spec.',
    state: 'visible',
    ownerId: 'current-user',
    categories: ['Health'],
    createdBy: 'current-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '5',
    headline: 'Housing affordability series',
    description: 'First piece in a series on housing affordability and rent trends in the region. Minimum 140 characters required so we add this extra text to meet the story model requirement.',
    state: 'visible',
    ownerId: 'current-user',
    categories: ['Housing', 'Series'],
    createdBy: 'current-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '6',
    headline: 'Week in review',
    description: 'Summary of the week\'s top stories and upcoming coverage. Description field requires at least 140 characters so we include this padding to satisfy the data model validation.',
    state: 'archived',
    ownerId: 'other-user',
    categories: [],
    createdBy: 'other-user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
